// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageData(arg1:string):Promise<string>;

export function LaunchSearch(arg1:string):Promise<void>;

export function OpenFileExplorer(arg1:string):Promise<void>;
