// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitSearchResult() {
  return window['go']['app']['App']['EmitSearchResult']();
}

export function GetImageData(arg1) {
  return window['go']['app']['App']['GetImageData'](arg1);
}

export function LaunchSearch(arg1) {
  return window['go']['app']['App']['LaunchSearch'](arg1);
}

export function OpenFileExplorer(arg1) {
  return window['go']['app']['App']['OpenFileExplorer'](arg1);
}
