// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitSearchResult():Promise<void>;

export function LaunchSearch(arg1:string):Promise<void>;
